version: '3.8'
services:
  mysql-db: 
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:  
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always
  backend-app: 
    build: .
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}  
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}  
      JWT_SECRET: ${JWT_SECRET}   
    ports:
      - "8080:8080"
    container_name: backend-app

volumes:
  mysql_data: