spring:
  application:
    name: backend-orii

  datasource:
    url: jdbc.mysql://localhost:3306/orii
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    date-format: dd-MM-yyyy
    time-zone: UTC

# Gmail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  servlet:
    context-path: /api/v1

api_url: http://localhost:8080${server.servlet.context-path}
jwt.secret: ${JWT_SECRET}
