spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always  
      
# Maildev configuration
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  servlet:
    context-path: /api/v1

api_url: http://localhost:8080${server.servlet.context-path}